<a href="https://colab.research.google.com/github/yuval728/Torch-learning/blob/master/00_base.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.2.1+cu121


## Intro to tensros

### creating tensors

In [2]:
# scalar
scalar=torch.tensor(7)
print(scalar, scalar.ndim, scalar.item())

tensor(7) 0 7


In [3]:
#vector
vector=torch.tensor([7,7])
print(vector, vector.ndim)
print(vector.shape)

tensor([7, 7]) 1
torch.Size([2])


In [4]:
#matrix
Matrix=torch.tensor([[7,8,9],[1,2,3]])
print(Matrix,Matrix.ndim)
print(Matrix.shape)

tensor([[7, 8, 9],
        [1, 2, 3]]) 2
torch.Size([2, 3])


In [5]:
#Tensor
Tensor=torch.tensor([[[1,2,3],[4,5,6],[7,8,9] ]])
print(Tensor,Tensor.ndim)
print(Tensor.shape)

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]]) 3
torch.Size([1, 3, 3])


In [6]:
#Random tensors
random_tensor=torch.rand(3,4)
print(random_tensor)

tensor([[8.6766e-04, 8.6907e-01, 7.4503e-01, 6.1361e-01],
        [7.3923e-03, 7.4612e-01, 7.1894e-01, 5.0885e-01],
        [2.6881e-01, 1.3968e-01, 9.4795e-01, 7.6160e-01]])


In [7]:
rand_image_tensor=torch.rand(size=(224,224,3))
rand_image_tensor.shape, rand_image_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [8]:
zeros=torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [9]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [10]:
ones=torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [11]:
ones.dtype

torch.float32

## Creating a range of tensors and tensors-like


In [12]:
one_to_ten=torch.arange(start=0, end=10, step=2)
one_to_ten

tensor([0, 2, 4, 6, 8])

In [13]:
zeros_like=torch.zeros_like(input=one_to_ten)
zeros_like

tensor([0, 0, 0, 0, 0])

## Tensor Datatypes and attributes

In [14]:
dtype=torch.tensor([3.0,6.0,9.0],
                  dtype=None, #torch.float32, etc
                  device='cpu', #'cuda' what device is your tensor on
                  requires_grad=False # To track gradients
                  )
dtype, dtype.dtype

(tensor([3., 6., 9.]), torch.float32)

In [15]:
float_16_tensor=dtype.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [16]:
float_16_tensor.dtype, float_16_tensor.shape, float_16_tensor.device

(torch.float16, torch.Size([3]), device(type='cpu'))

In [17]:
tensor=torch.tensor([1,2,3])
tensor

tensor([1, 2, 3])

In [18]:
tensor+10, tensor-1, tensor*10, tensor/10

(tensor([11, 12, 13]),
 tensor([0, 1, 2]),
 tensor([10, 20, 30]),
 tensor([0.1000, 0.2000, 0.3000]))

In [19]:
tensor*10, torch.mul(tensor,10)

(tensor([10, 20, 30]), tensor([10, 20, 30]))

In [20]:
torch.matmul(tensor,tensor)

tensor(14)

In [21]:
tensor @ tensor  #short form for matmul

tensor(14)

In [22]:
torch.rand(2,3) @ torch.rand(3,2)

tensor([[0.9950, 0.9535],
        [0.6074, 0.5609]])

In [23]:
torch.mm(torch.rand(2,3), torch.rand(2,3).T) #other name for matmul

tensor([[1.3541, 0.8699],
        [0.8512, 0.5176]])

## Tensors Aggregation function

In [24]:
x=torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [25]:
x.min(), torch.min(x)

(tensor(0), tensor(0))

In [26]:
x.max(), x.type(torch.float32).mean(), x.sum()

(tensor(90), tensor(45.), tensor(450))

In [27]:
x.argmin(), x.argmax()

(tensor(0), tensor(9))

## Reshaping Stacking Viewing Squeezing Unsqueezing Permuting


In [28]:
x_reshaped=x.reshape(2,5)
x_reshaped, x

(tensor([[ 0, 10, 20, 30, 40],
         [50, 60, 70, 80, 90]]),
 tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]))

In [29]:
z=x.view(1,10)
z,z.shape

(tensor([[ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]]), torch.Size([1, 10]))

In [30]:
z[:,0]=5
z,x  #both gets changed

(tensor([[ 5, 10, 20, 30, 40, 50, 60, 70, 80, 90]]),
 tensor([ 5, 10, 20, 30, 40, 50, 60, 70, 80, 90]))

In [31]:
x_vstacked=torch.stack([x,x,x,x], dim=0) #or torch.vstack
x_vstacked

tensor([[ 5, 10, 20, 30, 40, 50, 60, 70, 80, 90],
        [ 5, 10, 20, 30, 40, 50, 60, 70, 80, 90],
        [ 5, 10, 20, 30, 40, 50, 60, 70, 80, 90],
        [ 5, 10, 20, 30, 40, 50, 60, 70, 80, 90]])

In [32]:
x_hstacked=torch.stack([x,x,x,x], dim=1) #or torch.hstack
x_hstacked

tensor([[ 5,  5,  5,  5],
        [10, 10, 10, 10],
        [20, 20, 20, 20],
        [30, 30, 30, 30],
        [40, 40, 40, 40],
        [50, 50, 50, 50],
        [60, 60, 60, 60],
        [70, 70, 70, 70],
        [80, 80, 80, 80],
        [90, 90, 90, 90]])

In [33]:
x_reshaped=x.reshape(1,10)

In [34]:
x_reshaped.shape, x_reshaped.squeeze().shape #removes single dimensions

(torch.Size([1, 10]), torch.Size([10]))

In [35]:
x_reshaped.squeeze().unsqueeze(0),x_reshaped.squeeze().unsqueeze(0).shape

(tensor([[ 5, 10, 20, 30, 40, 50, 60, 70, 80, 90]]), torch.Size([1, 10]))

In [36]:
original=torch.rand((224,224,3))
original

tensor([[[0.6250, 0.7094, 0.6926],
         [0.2962, 0.5001, 0.5711],
         [0.4491, 0.3852, 0.6257],
         ...,
         [0.8236, 0.8703, 0.9510],
         [0.4641, 0.9950, 0.6770],
         [0.7190, 0.9121, 0.8786]],

        [[0.8244, 0.4694, 0.3700],
         [0.8170, 0.5456, 0.6430],
         [0.2788, 0.7211, 0.1072],
         ...,
         [0.7417, 0.0111, 0.4771],
         [0.8347, 0.3324, 0.5567],
         [0.4619, 0.7577, 0.9539]],

        [[0.4152, 0.2914, 0.9881],
         [0.3870, 0.7922, 0.7072],
         [0.2974, 0.0498, 0.0099],
         ...,
         [0.6320, 0.2388, 0.8828],
         [0.1250, 0.4320, 0.1739],
         [0.6909, 0.3107, 0.4155]],

        ...,

        [[0.4549, 0.9524, 0.6836],
         [0.1335, 0.0641, 0.0892],
         [0.3214, 0.3075, 0.5662],
         ...,
         [0.2667, 0.4464, 0.2652],
         [0.7185, 0.4282, 0.6481],
         [0.3855, 0.6702, 0.5761]],

        [[0.7480, 0.4771, 0.4193],
         [0.7497, 0.9891, 0.0617],
         [0.

In [37]:
permutted=torch.permute(original,(2,0,1))
permutted

tensor([[[0.6250, 0.2962, 0.4491,  ..., 0.8236, 0.4641, 0.7190],
         [0.8244, 0.8170, 0.2788,  ..., 0.7417, 0.8347, 0.4619],
         [0.4152, 0.3870, 0.2974,  ..., 0.6320, 0.1250, 0.6909],
         ...,
         [0.4549, 0.1335, 0.3214,  ..., 0.2667, 0.7185, 0.3855],
         [0.7480, 0.7497, 0.6086,  ..., 0.5558, 0.0342, 0.3530],
         [0.4661, 0.7804, 0.1232,  ..., 0.9769, 0.9154, 0.0604]],

        [[0.7094, 0.5001, 0.3852,  ..., 0.8703, 0.9950, 0.9121],
         [0.4694, 0.5456, 0.7211,  ..., 0.0111, 0.3324, 0.7577],
         [0.2914, 0.7922, 0.0498,  ..., 0.2388, 0.4320, 0.3107],
         ...,
         [0.9524, 0.0641, 0.3075,  ..., 0.4464, 0.4282, 0.6702],
         [0.4771, 0.9891, 0.1396,  ..., 0.7525, 0.7797, 0.0176],
         [0.2059, 0.2327, 0.1147,  ..., 0.6893, 0.3790, 0.4211]],

        [[0.6926, 0.5711, 0.6257,  ..., 0.9510, 0.6770, 0.8786],
         [0.3700, 0.6430, 0.1072,  ..., 0.4771, 0.5567, 0.9539],
         [0.9881, 0.7072, 0.0099,  ..., 0.8828, 0.1739, 0.

In [38]:
original.shape, permutted.shape
#changing one value in permutted also gets changed in original

(torch.Size([224, 224, 3]), torch.Size([3, 224, 224]))

## Numpy Pytorch

In [39]:
array=np.arange(1.0,10.0)
tensor=torch.from_numpy(array)
array,tensor

(array([1., 2., 3., 4., 5., 6., 7., 8., 9.]),
 tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=torch.float64))

In [40]:
tensor.numpy()

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [41]:
seed=42
torch.manual_seed(seed)
seed_tensor=torch.rand(3,3)
torch.manual_seed(seed)
seed_tensor2=torch.rand(3,3)
seed_tensor,seed_tensor2

(tensor([[0.8823, 0.9150, 0.3829],
         [0.9593, 0.3904, 0.6009],
         [0.2566, 0.7936, 0.9408]]),
 tensor([[0.8823, 0.9150, 0.3829],
         [0.9593, 0.3904, 0.6009],
         [0.2566, 0.7936, 0.9408]]))

## Checking CUDA

In [42]:
torch.cuda.is_available()

True

In [43]:
device= 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cuda'

In [44]:
torch.cuda.device_count()

1

In [46]:
tensor=torch.tensor([1,2,3,], device=device)
tensor.device

device(type='cuda', index=0)

In [48]:
cputensor=torch.tensor([4,4,5],device='cpu')
cputensor, cputensor.to(device)

(tensor([4, 4, 5]), tensor([4, 4, 5], device='cuda:0'))

In [51]:
tensor.cpu()  ## Need to because numpy cannot work with tensors no GPU

tensor([1, 2, 3])

In [52]:
tensor.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [53]:
tensor.cpu().numpy()

array([1, 2, 3])